TRT:
  engine: Face Detection
  model_name:
   two: SCRTRT_2
   ten: SCRTRT_10
  backend: tritonserver
  url: localhost:8001
  input_size:
    width: 640
    height: 640
  batch_size: 4
  iou_threshold: 0.35
  conf_threshold: 0.5
  nms_thresh: 0.4
  mean: 127.5
  fpn_stride:
    - 8
    - 16
    - 32
  fmc: 3
  num_anchors: 2
  model_info: false
  verbose: false
